---
- name: Pull image from repository
  docker_image:
    name: "{{backend_docker_image}}"
    tag: v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: gicheha-backend
    image: "{{backend_docker_image_version}}"
    network_mode: host
    ports:
      - "5000:5000"
  become: yes