---
- name: Pull image from repository
  docker_image:
    name: gicheha/ip_backend
    tag: v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: gicheha-backend
    image: gicheha/ip_backend:v1.0.0
    network_mode: host
    ports:
      - "5000:5000"
  become: yes