---
# roles/frontend/tasks/main.yml

- name: Pull frontend Docker image
  docker_image:
    name: "{{fronted_image}}"
    tag: "{{fronted_image_version}}"
    source: pull

- name: Run frontend Docker container
  docker_container:
    name: client-react-app
    image: gicheha/ip_frontend:v1.0.0
    state: started
    ports:
      - "80:80"
    network_mode: host
    restart_policy: always
  become: true
