---
- name: Create Docker network
  docker_network:
    name: "{{mongo_network}}"
    state: present

- name: Run MongoDB Container
  docker_container:
    name: "{{mongo_container_name}}"
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - "{{mongo_volume}}"
    network_mode: host
  tags:
    - database
    - backend