---
- name: Create Docker network
  docker_network:
    name: app-net
    state: present

- name: Run MongoDB Container
  docker_container:
    name: app-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./app-mongo-data:/data/db
    network_mode: host
  tags:
    - database
    - backend