---
- name: Pull image from repository
  docker_image:
    name: gicheha/ip_backend
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: gicheha-backend
    image: gicheha/ip_backend
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes